version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: DB-helpdesk
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: helpdeskdb
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: helpdesk
      MYSQL_PASSWORD: helpdesk
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
